apiVersion: v1
kind: Service
metadata:
  name: custom-service
  labels:
    app: custom-devops-project
spec:
  type: NodePort
  selector:
    app: custom-devops-project
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200